import type { Metadata } from "next";
import { Alike, Sarabun } from "next/font/google";
import "./globals.css";

const alike = Alike({
  variable: "--font-geist-alike",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"]
});

const sarabun = Sarabun({
  variable: "--font-geist-sarabun",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alike.variable} ${sarabun.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
